### ISSUE TITLE
Provide Immutable types

### ISSUE THREAD

**Issue by bruno-ds** [alphametric/strong-native-types#1]
Hello,
I juste read your great article on medium, and came here to read the code.

You provide two variations: nullable and not-nullable, 
I suggest that you add mutable (this is your existing code) and Immutable.

**Comment by alphametric** [comment]
Great idea!

I've updated the package to include this functionality. See the immutability section in the revised [readme](https://github.com/alphametric/strong-native-types#immutability).

**Comment by bruno-ds** [comment]
I'm sorry, but I think that Immutability shouldn't be mutable : in order to be useful it is a contract that cannot change.
see wikipedia :
> an immutable object is an object whose state cannot be modified after it is created.
